/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PARCIAL_1.Config.Prin;

import javax.swing.table.DefaultTableModel;

public class añadir extends javax.swing.JFrame {
    private DefaultTableModel modelo;
    private Jtable ventanaPrincipal; // Agregar una referencia a la ventana principal

    public añadir(Jtable ventanaPrincipal) {
        initComponents();
        modelo = (DefaultTableModel) TablaAñadir.getModel();
        this.ventanaPrincipal = ventanaPrincipal; // Inicializar la referencia a la ventana principal
        
        añadirMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirMasActionPerformed(evt);
            }
        });

        añadirMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirMenosActionPerformed(evt);
            }
        });

        añadirOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirOkActionPerformed(evt);
            }
        });
    }
    
    public void agregarProducto(String codigo, String nombre, float precio, int cantidad, String fecha) {
        DefaultTableModel modelo = (DefaultTableModel) TablaAñadir.getModel();
        modelo.addRow(new Object[]{codigo, nombre, precio, cantidad, fecha});
    }
        
    private int selectedRowIndex = -1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAñadir = new javax.swing.JTextField();
        cantidadaañadir = new javax.swing.JLabel();
        añadirMas = new javax.swing.JButton();
        añadirMenos = new javax.swing.JButton();
        añadirOk = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaAñadir = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAñadirActionPerformed(evt);
            }
        });

        cantidadaañadir.setText("CANTIDAD A AÑADIR:");

        añadirMas.setText("+");
        añadirMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirMasActionPerformed(evt);
            }
        });

        añadirMenos.setText("-");
        añadirMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirMenosActionPerformed(evt);
            }
        });

        añadirOk.setText("OK");
        añadirOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirOkActionPerformed(evt);
            }
        });

        TablaAñadir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Cantidad", "Fecha", "Total"
            }
        ));
        TablaAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaAñadirMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablaAñadir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cantidadaañadir)
                        .addGap(18, 18, 18)
                        .addComponent(txtAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(añadirMas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(añadirMenos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(añadirOk)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadaañadir)
                    .addComponent(txtAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añadirMas)
                    .addComponent(añadirMenos)
                    .addComponent(añadirOk))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirMasActionPerformed
            String cantidadStr = txtAñadir.getText();

        if (!cantidadStr.isEmpty()) {
            int cantidad = Integer.parseInt(cantidadStr);
            cantidad++;
            txtAñadir.setText(String.valueOf(cantidad));
        }
    }//GEN-LAST:event_añadirMasActionPerformed

    private void añadirMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirMenosActionPerformed
            String cantidadStr = txtAñadir.getText();

        if (!cantidadStr.isEmpty()) {
            int cantidad = Integer.parseInt(cantidadStr);
            if (cantidad > 0) {
                cantidad--;
                txtAñadir.setText(String.valueOf(cantidad));
            }
        }
    }//GEN-LAST:event_añadirMenosActionPerformed

    private void añadirOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirOkActionPerformed
       // Guardar los productos en tu lógica de negocio aquí
        // Por ejemplo, puedes recorrer la tabla y obtener los datos
        DefaultTableModel modelo = (DefaultTableModel) TablaAñadir.getModel();
        int filas = modelo.getRowCount();

        for (int fila = 0; fila < filas; fila++) {
            String codigo = modelo.getValueAt(fila, 0).toString();
            String nombre = modelo.getValueAt(fila, 1).toString();
            float precio = Float.parseFloat(modelo.getValueAt(fila, 2).toString());
            int cantidad = Integer.parseInt(modelo.getValueAt(fila, 3).toString());
            String fecha = modelo.getValueAt(fila, 4).toString();

            // Guardar estos datos en tu lógica de negocio
            // Por ejemplo, agregarlos a una lista de productos
        }

        // Cerrar la ventana o realizar otras acciones necesarias
        this.dispose();
    
    }//GEN-LAST:event_añadirOkActionPerformed

    private void txtAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñadirActionPerformed

    private void TablaAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaAñadirMouseClicked
            int fila = TablaAñadir.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "No se seleccionó una fila");
    } else {
        // Obtener los datos de la fila seleccionada
        String codigo = TablaAñadir.getValueAt(fila, 0).toString();
        String nombre = TablaAñadir.getValueAt(fila, 1).toString();
        float precio = Float.parseFloat(TablaAñadir.getValueAt(fila, 2).toString());
        int cantidad = Integer.parseInt(TablaAñadir.getValueAt(fila, 3).toString());
        String fecha = TablaAñadir.getValueAt(fila, 4).toString();

        // Agregar los datos a la tabla de la ventana principal
        ventanaPrincipal.agregarProducto(codigo, nombre, precio, cantidad, fecha);
    }
    }//GEN-LAST:event_TablaAñadirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new añadir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaAñadir;
    private javax.swing.JButton añadirMas;
    private javax.swing.JButton añadirMenos;
    private javax.swing.JButton añadirOk;
    private javax.swing.JLabel cantidadaañadir;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtAñadir;
    // End of variables declaration//GEN-END:variables
}
